#!/bin/bash

FIXTURES_DIR="${BATS_TEST_DIRNAME}/fixtures"
SOURCE_DIR="${BATS_TEST_DIRNAME}/../../.."
TASKS_DIR="${SOURCE_DIR}/src/tasks"
PROJECT_ROOT_DIR="${BATS_TEST_DIRNAME}/../../../../"
COMMON_DIR="${FIXTURES_DIR}/scripts"

export FIXTURES_DIR SOURCE_DIR TASKS_DIR PROJECT_ROOT_DIR COMMON_DIR
